# api config
server.servlet.context-path=/api
server.port=8085

# jwt config
#jwt.secret=htv
jwt.secret=s1st3m44Dm1nB4ck3ndHtvH4bT3cn0l0g1c0V1rtu4l2025
jwt.expiration=3000
jwt.refreshExpiration=6000

# redis config
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.timeout=60
# spring.redis.password=redis123

# bd config
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/htv
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.continue-on-error=true
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false
spring.jpa.open-in-view=true

# IE config dev
ie.url.authorization=https://devidentidad.mitic.gov.py/login?clientId=1127&scope=read&responseType=code
ie.url.authentication=https://devidentidad.mitic.gov.py/rest/
ie.client.id=1127
ie.secret=ee7621b2-3041-4601-a893-bbb236a41afd
ie.issuer=SENATICs

# develop
spring.devtools.reload.trigger-file=.reloadtrigger

# SpringDoc OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.packagesToScan=py.gov.mitic.htv.controller
#springdoc.pathsToMatch=/usuario/**, /auditoria/**, /institucion/**, /auth/**

spring.flyway.enabled=true
spring.flyway.configFiles=classpath:flyway.conf

max.file.size.mb=12
allowed.file.extensions=png,jpg,jpeg,gif,mp4,mov,avi,pdf
allowed.image.extensions=png,jpg,jpeg,gif
allowed.document.extensions=pdf,doc,docx,txt,xls,xlsx
allowed.video.extensions=mp4,mov,avi

# mongoDB config
spring.data.mongodb.authentication-database=archivos
spring.data.mongodb.host=localhost
spring.data.mongodb.database=archivos
spring.data.mongodb.port=27017
spring.data.mongodb.username=denuncia
spring.data.mongodb.password=d3nunc1a


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tu-correo@gmail.com
spring.mail.password=tuContrasenhaDeAplicacionDe16Digitos
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
mail.from.sender=no-responder@paraguay.gov.py

htv.admin.linK.acceso.plataforma = http://192.168.211.10:8096/
htv.landing.linK.acceso.plataforma = http://192.168.211.10:8094/
htv.admin.validacion.codigo.expirado.minutos = 5

