# api config
server.servlet.context-path=/api
server.port=8083
spring.mvc.locale=es_ES

# jwt config
jwt.secret=htvadminweb_super_secret_key_2025_secure_random!
jwt.expiration=3000000
jwt.refreshExpiration=6000000

# redis config
#spring.redis.host=localhost
spring.redis.host=192.168.211.10
spring.redis.port=6379
spring.redis.timeout=60
spring.redis.password=123456

# bd config
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://192.168.211.10:5432/htv
spring.datasource.username=postgres
spring.datasource.password=d3n4nc1a
spring.datasource.continue-on-error=true
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false
spring.jpa.open-in-view=true
spring.datasource.sql-script-encoding = UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# config file
max.file.size.mb=20
allowed.file.extensions=doc,docx,pdf,txt,xls,xlsx,png,jpg,jpeg,gif,zip,avi,mov,mp4

# IE config dev
ie.url.authorization=https://devidentidad.mitic.gov.py/login?clientId=1127&scope=read&responseType=code
ie.url.authentication=https://devidentidad.mitic.gov.py/rest/
ie.client.id=1127
ie.secret=ee7621b2-3041-4601-a893-bbb236a41afd
ie.issuer=SENATICs

# SpringDoc OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.packagesToScan=py.gov.mitic.htv.controller
#springdoc.pathsToMatch=/usuario/**, /auditoria/**, /institucion/**, /auth/**

spring.flyway.enabled=true
spring.flyway.configFiles=classpath:flyway.conf

max.file.size.mb=10
allowed.file.extensions=png,jpg,jpeg,gif,mp4,mov,avi,pdf
allowed.image.extensions=png,jpg,jpeg,gif
allowed.document.extensions=pdf,doc,docx,txt,xls,xlsx

logging:
  level:
    org.springframework.web: DEBUG

# mongoDB config
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.host=mongodb_container
spring.data.mongodb.database=archivos
spring.data.mongodb.port=27017
spring.data.mongodb.username=root
spring.data.mongodb.password=r00t4rch1vos
spring.jackson.serialization.INDENT_OUTPUT=true

# Config del servidor SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=viictori19.vc@gmail.com
spring.mail.password=aefg uyzy fzqg dttb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
mail.from.sender=no-responder@paraguay.gov.py



htv.admin.linK.acceso.plataforma = http://192.168.211.10:8096/
htv.landing.linK.acceso.plataforma = http://192.168.211.10:8094/
htv.admin.validacion.codigo.expirado.minutos = 5

# develop
spring.devtools.reload.trigger-file=.reloadtrigger