
ALTER TABLE formulario ADD COLUMN funciones jsonb NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE formulario ADD CONSTRAINT formulario_funciones_array CHECK (jsonb_typeof(funciones) = 'array');
ALTER TABLE tramite ADD COLUMN funciones_ejecutadas jsonb NOT NULL DEFAULT '{}'::jsonb;
CREATE TABLE tramite_funcion_ejecucion (
    id_tramite_funcion_ejecucion bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tramite bigint NOT NULL,
    id_formulario bigint NOT NULL,
    id_usuario bigint NOT NULL REFERENCES usuario(id_usuario),
    version_solicitada bigint NOT NULL,
    configuracion varchar(80) NOT NULL,
    estado varchar(30) NOT NULL CHECK (estado IN ('CONSULTANDO','ENCONTRADO','NO_ENCONTRADO','ERROR','DESACTUALIZADA')),
    creado_en timestamptz NOT NULL DEFAULT now(),
    entradas jsonb NOT NULL DEFAULT '{}'::jsonb,
    salidas jsonb NOT NULL DEFAULT '{}'::jsonb,
    FOREIGN KEY (id_tramite, id_formulario) REFERENCES tramite(id_tramite, id_formulario)
);
CREATE INDEX tramite_funcion_consultas_idx ON tramite_funcion_ejecucion(id_tramite, creado_en DESC);
