-- Módulo de trámites. Aplicar después de V3 en una base ANTSV.
CREATE TABLE public.tipo_tramite (
    id_tipo_tramite bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo text,
    nombre text,
    descripcion text,
    activo boolean NOT NULL DEFAULT false,
    permite_solicitud boolean NOT NULL DEFAULT false,
    orden integer NOT NULL DEFAULT 0
);
CREATE TABLE public.formulario (
    id_formulario bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tipo_tramite bigint,
    nombre text,
    numero_version integer NOT NULL DEFAULT 0,
    estado text,
    version bigint NOT NULL DEFAULT 0,
    creado_por bigint,
    actualizado_por bigint,
    creado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fundamento_publicacion text,
    publicado_en timestamptz
);
CREATE TABLE public.formulario_seccion (
    id_formulario_seccion bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_formulario bigint,
    codigo text,
    titulo text,
    orden integer NOT NULL DEFAULT 0
);
CREATE TABLE public.formulario_grupo (
    id_formulario_grupo bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_formulario bigint,
    seccion text,
    codigo text,
    nombre text,
    minimo integer NOT NULL DEFAULT 0,
    maximo integer NOT NULL DEFAULT 0,
    orden integer NOT NULL DEFAULT 0
);
CREATE TABLE public.formulario_campo (
    id_formulario_campo bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_formulario bigint,
    seccion text,
    grupo text,
    codigo text,
    etiqueta text,
    ayuda text,
    tipo text,
    requerido boolean NOT NULL DEFAULT false,
    longitud_maxima integer,
    minimo numeric,
    maximo numeric,
    orden integer NOT NULL DEFAULT 0
);
CREATE TABLE public.campo_opcion (
    id_campo_opcion bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_formulario bigint,
    campo text,
    codigo text,
    etiqueta text,
    orden integer NOT NULL DEFAULT 0
);
CREATE TABLE public.formulario_requisito (
    id_formulario_requisito bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_formulario bigint,
    codigo text,
    nombre text,
    descripcion text,
    minimo integer NOT NULL DEFAULT 0,
    maximo integer NOT NULL DEFAULT 0,
    tamanio_maximo_mb integer NOT NULL DEFAULT 0,
    extensiones text,
    orden integer NOT NULL DEFAULT 0
);
CREATE TABLE public.formulario_regla (
    id_formulario_regla bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_formulario bigint,
    origen text,
    destino text,
    operador text,
    valor text,
    accion text
);
CREATE TABLE public.tramite (
    id_tramite bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero text,
    id_formulario bigint,
    id_solicitante bigint,
    id_responsable bigint,
    estado text,
    version bigint NOT NULL DEFAULT 0,
    creado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    presentado_en timestamptz,
    finalizado_en timestamptz
);
CREATE TABLE public.tramite_grupo_instancia (
    id_tramite_grupo_instancia bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tramite bigint,
    id_formulario bigint,
    grupo text,
    instancia text,
    orden integer NOT NULL DEFAULT 0
);
CREATE TABLE public.tramite_respuesta (
    id_tramite_respuesta bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tramite bigint,
    id_formulario bigint,
    campo text,
    instancia text,
    valor_texto text,
    valor_numero numeric,
    valor_fecha date,
    valor_booleano boolean,
    valor_json jsonb
);
CREATE TABLE public.tramite_archivo (
    id_tramite_archivo bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tramite bigint,
    id_formulario bigint,
    requisito text,
    referencia text,
    nombre text,
    mime text,
    tamanio bigint NOT NULL DEFAULT 0,
    hash text,
    activo boolean NOT NULL DEFAULT false,
    creado_por bigint,
    creado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE public.tramite_evento (
    id_tramite_evento bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tramite bigint,
    id_usuario bigint,
    accion text,
    estado_anterior text,
    estado_nuevo text,
    observacion text,
    visible_solicitante boolean NOT NULL DEFAULT false,
    fecha timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE public.tramite_revision (
    id_tramite_revision bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tramite bigint,
    id_usuario bigint,
    version_presentada bigint,
    clave_presentacion text,
    contenido jsonb,
    fecha timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE tipo_tramite ADD UNIQUE (codigo);
ALTER TABLE tipo_tramite ALTER COLUMN codigo SET NOT NULL;
ALTER TABLE tipo_tramite ALTER COLUMN nombre SET NOT NULL;
ALTER TABLE formulario ADD FOREIGN KEY (id_tipo_tramite) REFERENCES tipo_tramite;
ALTER TABLE formulario ADD UNIQUE (id_tipo_tramite, numero_version);
ALTER TABLE formulario ADD CHECK (estado IN ('BORRADOR','PUBLICADO','RETIRADO'));
CREATE UNIQUE INDEX formulario_publicado_unico ON formulario(id_tipo_tramite) WHERE estado = 'PUBLICADO';
ALTER TABLE formulario_seccion ADD FOREIGN KEY (id_formulario) REFERENCES formulario;
CREATE INDEX formulario_seccion_formulario_idx ON formulario_seccion(id_formulario);
ALTER TABLE formulario_grupo ADD FOREIGN KEY (id_formulario) REFERENCES formulario;
CREATE INDEX formulario_grupo_formulario_idx ON formulario_grupo(id_formulario);
ALTER TABLE formulario_campo ADD FOREIGN KEY (id_formulario) REFERENCES formulario;
CREATE INDEX formulario_campo_formulario_idx ON formulario_campo(id_formulario);
ALTER TABLE formulario_requisito ADD FOREIGN KEY (id_formulario) REFERENCES formulario;
CREATE INDEX formulario_requisito_formulario_idx ON formulario_requisito(id_formulario);
ALTER TABLE formulario_regla ADD FOREIGN KEY (id_formulario) REFERENCES formulario;
CREATE INDEX formulario_regla_formulario_idx ON formulario_regla(id_formulario);
ALTER TABLE campo_opcion ADD FOREIGN KEY (id_formulario) REFERENCES formulario;
CREATE INDEX campo_opcion_formulario_idx ON campo_opcion(id_formulario);
ALTER TABLE formulario_seccion ADD UNIQUE (id_formulario, codigo);
ALTER TABLE formulario_grupo ADD UNIQUE (id_formulario, codigo);
ALTER TABLE formulario_campo ADD UNIQUE (id_formulario, codigo);
ALTER TABLE formulario_requisito ADD UNIQUE (id_formulario, codigo);

ALTER TABLE formulario_grupo ADD FOREIGN KEY (id_formulario, seccion) REFERENCES formulario_seccion(id_formulario, codigo);
ALTER TABLE formulario_grupo ADD UNIQUE (id_formulario, codigo, seccion);
ALTER TABLE formulario_campo ADD FOREIGN KEY (id_formulario, seccion) REFERENCES formulario_seccion(id_formulario, codigo);
ALTER TABLE formulario_campo ADD FOREIGN KEY (id_formulario, grupo, seccion) REFERENCES formulario_grupo(id_formulario, codigo, seccion);
ALTER TABLE campo_opcion ADD FOREIGN KEY (id_formulario, campo) REFERENCES formulario_campo(id_formulario, codigo);
ALTER TABLE campo_opcion ADD UNIQUE (id_formulario, campo, codigo);
ALTER TABLE formulario_regla ADD FOREIGN KEY (id_formulario, origen) REFERENCES formulario_campo(id_formulario, codigo);
ALTER TABLE tramite ADD FOREIGN KEY (id_formulario) REFERENCES formulario;
ALTER TABLE tramite ADD FOREIGN KEY (id_solicitante) REFERENCES usuario;
ALTER TABLE tramite ADD FOREIGN KEY (id_responsable) REFERENCES usuario;
ALTER TABLE tramite ADD UNIQUE (numero);
ALTER TABLE tramite ADD UNIQUE (id_tramite, id_formulario);
ALTER TABLE tramite ALTER COLUMN id_solicitante SET NOT NULL;
ALTER TABLE tramite ALTER COLUMN id_formulario SET NOT NULL;
ALTER TABLE tramite ADD CHECK (estado IN ('BORRADOR','PRESENTADO','RECIBIDO','EN_REVISION','OBSERVADO','SUBSANACION','EN_EVALUACION','APROBADO','RECHAZADO','FINALIZADO','CANCELADO'));
CREATE INDEX tramite_solicitante_idx ON tramite(id_solicitante, actualizado_en DESC);
CREATE INDEX tramite_bandeja_idx ON tramite(estado, id_responsable, actualizado_en DESC);
ALTER TABLE tramite_grupo_instancia ADD UNIQUE (id_tramite, instancia);
ALTER TABLE tramite_grupo_instancia ADD FOREIGN KEY (id_formulario, grupo) REFERENCES formulario_grupo(id_formulario, codigo);
ALTER TABLE tramite_respuesta ADD FOREIGN KEY (id_formulario, campo) REFERENCES formulario_campo(id_formulario, codigo);
ALTER TABLE tramite_respuesta ADD FOREIGN KEY (id_tramite, instancia) REFERENCES tramite_grupo_instancia(id_tramite, instancia);
ALTER TABLE tramite_respuesta ADD CHECK (num_nonnulls(valor_texto, valor_numero, valor_fecha, valor_booleano, valor_json) = 1);
CREATE UNIQUE INDEX tramite_respuesta_simple_unica ON tramite_respuesta(id_tramite, campo) WHERE instancia IS NULL;
CREATE UNIQUE INDEX tramite_respuesta_fila_unica ON tramite_respuesta(id_tramite, campo, instancia) WHERE instancia IS NOT NULL;
ALTER TABLE tramite_archivo ADD FOREIGN KEY (id_formulario, requisito) REFERENCES formulario_requisito(id_formulario, codigo);
ALTER TABLE tramite_revision ADD UNIQUE (id_tramite, clave_presentacion);
ALTER TABLE tramite_revision ADD UNIQUE (id_tramite, version_presentada);
ALTER TABLE tramite_grupo_instancia ADD FOREIGN KEY (id_tramite, id_formulario) REFERENCES tramite(id_tramite, id_formulario);
ALTER TABLE tramite_respuesta ADD FOREIGN KEY (id_tramite, id_formulario) REFERENCES tramite(id_tramite, id_formulario);
ALTER TABLE tramite_archivo ADD FOREIGN KEY (id_tramite, id_formulario) REFERENCES tramite(id_tramite, id_formulario);
ALTER TABLE tramite_evento ADD FOREIGN KEY (id_tramite) REFERENCES tramite;
ALTER TABLE tramite_revision ADD FOREIGN KEY (id_tramite) REFERENCES tramite;
CREATE INDEX tramite_grupo_instancia_tramite_idx ON tramite_grupo_instancia(id_tramite);
CREATE INDEX tramite_respuesta_tramite_idx ON tramite_respuesta(id_tramite);
CREATE INDEX tramite_archivo_tramite_idx ON tramite_archivo(id_tramite);
CREATE INDEX tramite_evento_tramite_idx ON tramite_evento(id_tramite);
CREATE INDEX tramite_revision_tramite_idx ON tramite_revision(id_tramite);

-- Catálogos de formularios; no duplica catálogos maestros institucionales existentes.
CREATE TABLE tramite_catalogo (
 id_tramite_catalogo bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 codigo text NOT NULL UNIQUE, nombre text NOT NULL, activo boolean NOT NULL DEFAULT true,
 version bigint NOT NULL DEFAULT 0, actualizado_por bigint REFERENCES usuario, actualizado_en timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE tramite_catalogo_item (
 id_tramite_catalogo_item bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_catalogo bigint NOT NULL REFERENCES tramite_catalogo,
 codigo text NOT NULL, etiqueta text NOT NULL, padre text, activo boolean NOT NULL DEFAULT true, orden integer NOT NULL DEFAULT 0,
 UNIQUE(id_catalogo,codigo), FOREIGN KEY(id_catalogo,padre) REFERENCES tramite_catalogo_item(id_catalogo,codigo) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX tramite_catalogo_item_padre_idx ON tramite_catalogo_item(id_catalogo,padre);
ALTER TABLE formulario_campo ADD COLUMN catalogo text REFERENCES tramite_catalogo(codigo);

ALTER TABLE tipo_tramite ADD COLUMN creado_por bigint REFERENCES usuario;
ALTER TABLE tipo_tramite ADD COLUMN actualizado_por bigint REFERENCES usuario;
ALTER TABLE tipo_tramite ADD COLUMN creado_en timestamptz NOT NULL DEFAULT now();
ALTER TABLE tipo_tramite ADD COLUMN actualizado_en timestamptz NOT NULL DEFAULT now();
CREATE TABLE tramite_asignacion (
 id_tramite_asignacion bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_tramite bigint NOT NULL REFERENCES tramite,
 id_responsable bigint NOT NULL REFERENCES usuario,
 asignado_por bigint NOT NULL REFERENCES usuario,
 inicio timestamptz NOT NULL, fin timestamptz,
 CHECK(fin IS NULL OR fin>=inicio)
);
CREATE UNIQUE INDEX tramite_asignacion_vigente ON tramite_asignacion(id_tramite) WHERE fin IS NULL;
CREATE INDEX tramite_asignacion_responsable_idx ON tramite_asignacion(id_responsable);
CREATE INDEX tramite_archivo_referencia_idx ON tramite_archivo(referencia);
ALTER TABLE formulario ALTER COLUMN id_tipo_tramite SET NOT NULL;
ALTER TABLE formulario ALTER COLUMN nombre SET NOT NULL;
ALTER TABLE formulario ALTER COLUMN estado SET NOT NULL;
ALTER TABLE formulario ALTER COLUMN numero_version SET NOT NULL;
ALTER TABLE formulario_seccion ALTER COLUMN id_formulario SET NOT NULL;
ALTER TABLE formulario_seccion ALTER COLUMN codigo SET NOT NULL;
ALTER TABLE formulario_seccion ALTER COLUMN titulo SET NOT NULL;
ALTER TABLE formulario_grupo ALTER COLUMN id_formulario SET NOT NULL;
ALTER TABLE formulario_grupo ALTER COLUMN seccion SET NOT NULL;
ALTER TABLE formulario_grupo ALTER COLUMN codigo SET NOT NULL;
ALTER TABLE formulario_grupo ALTER COLUMN nombre SET NOT NULL;
ALTER TABLE formulario_campo ALTER COLUMN id_formulario SET NOT NULL;
ALTER TABLE formulario_campo ALTER COLUMN seccion SET NOT NULL;
ALTER TABLE formulario_campo ALTER COLUMN codigo SET NOT NULL;
ALTER TABLE formulario_campo ALTER COLUMN etiqueta SET NOT NULL;
ALTER TABLE formulario_campo ALTER COLUMN tipo SET NOT NULL;
ALTER TABLE campo_opcion ALTER COLUMN id_formulario SET NOT NULL;
ALTER TABLE campo_opcion ALTER COLUMN campo SET NOT NULL;
ALTER TABLE campo_opcion ALTER COLUMN codigo SET NOT NULL;
ALTER TABLE campo_opcion ALTER COLUMN etiqueta SET NOT NULL;
ALTER TABLE formulario_requisito ALTER COLUMN id_formulario SET NOT NULL;
ALTER TABLE formulario_requisito ALTER COLUMN codigo SET NOT NULL;
ALTER TABLE formulario_requisito ALTER COLUMN nombre SET NOT NULL;
ALTER TABLE formulario_requisito ALTER COLUMN extensiones SET NOT NULL;
ALTER TABLE formulario_regla ALTER COLUMN id_formulario SET NOT NULL;
ALTER TABLE formulario_regla ALTER COLUMN origen SET NOT NULL;
ALTER TABLE formulario_regla ALTER COLUMN destino SET NOT NULL;
ALTER TABLE formulario_regla ALTER COLUMN operador SET NOT NULL;
ALTER TABLE formulario_regla ALTER COLUMN valor SET NOT NULL;
ALTER TABLE formulario_regla ALTER COLUMN accion SET NOT NULL;
ALTER TABLE tramite_grupo_instancia ALTER COLUMN id_tramite SET NOT NULL;
ALTER TABLE tramite_grupo_instancia ALTER COLUMN id_formulario SET NOT NULL;
ALTER TABLE tramite_grupo_instancia ALTER COLUMN grupo SET NOT NULL;
ALTER TABLE tramite_grupo_instancia ALTER COLUMN instancia SET NOT NULL;
ALTER TABLE tramite_respuesta ALTER COLUMN id_tramite SET NOT NULL;
ALTER TABLE tramite_respuesta ALTER COLUMN id_formulario SET NOT NULL;
ALTER TABLE tramite_respuesta ALTER COLUMN campo SET NOT NULL;
ALTER TABLE tramite_archivo ALTER COLUMN id_tramite SET NOT NULL;
ALTER TABLE tramite_archivo ALTER COLUMN id_formulario SET NOT NULL;
ALTER TABLE tramite_archivo ALTER COLUMN requisito SET NOT NULL;
ALTER TABLE tramite_archivo ALTER COLUMN referencia SET NOT NULL;
ALTER TABLE tramite_archivo ALTER COLUMN nombre SET NOT NULL;
ALTER TABLE tramite_archivo ALTER COLUMN mime SET NOT NULL;
ALTER TABLE tramite_archivo ALTER COLUMN hash SET NOT NULL;
ALTER TABLE tramite_archivo ALTER COLUMN creado_por SET NOT NULL;
ALTER TABLE tramite_evento ALTER COLUMN id_tramite SET NOT NULL;
ALTER TABLE tramite_evento ALTER COLUMN id_usuario SET NOT NULL;
ALTER TABLE tramite_evento ALTER COLUMN accion SET NOT NULL;
ALTER TABLE tramite_evento ALTER COLUMN estado_nuevo SET NOT NULL;
ALTER TABLE tramite_revision ALTER COLUMN id_tramite SET NOT NULL;
ALTER TABLE tramite_revision ALTER COLUMN id_usuario SET NOT NULL;
ALTER TABLE tramite_revision ALTER COLUMN version_presentada SET NOT NULL;
ALTER TABLE tramite_revision ALTER COLUMN clave_presentacion SET NOT NULL;
ALTER TABLE tramite_revision ALTER COLUMN contenido SET NOT NULL;
ALTER TABLE formulario_grupo ADD CHECK (minimo>=0 AND maximo>=greatest(1,minimo) AND maximo<=100);
ALTER TABLE formulario_requisito ADD CHECK (minimo>=0 AND maximo>=greatest(1,minimo) AND maximo<=10 AND tamanio_maximo_mb BETWEEN 1 AND 20);
ALTER TABLE formulario_campo ADD CHECK (tipo IN ('TEXT','TEXTAREA','EMAIL','NUMBER','DATE','BOOLEAN','SELECT','RADIO','MULTISELECT','MAP'));
ALTER TABLE formulario_campo ADD CHECK (minimo IS NULL OR maximo IS NULL OR minimo<=maximo);
ALTER TABLE formulario_regla ADD CHECK (operador IN ('IGUAL','DISTINTO') AND accion IN ('MOSTRAR_SI','REQUERIR_SI'));
ALTER TABLE formulario ADD CHECK (estado<>'PUBLICADO' OR (publicado_en IS NOT NULL AND fundamento_publicacion IS NOT NULL));
ALTER TABLE tramite_archivo ADD CHECK (tamanio>0 AND tamanio<=20971520);
ALTER TABLE formulario ADD FOREIGN KEY (creado_por) REFERENCES usuario;
ALTER TABLE formulario ADD FOREIGN KEY (actualizado_por) REFERENCES usuario;
ALTER TABLE tramite_archivo ADD FOREIGN KEY (creado_por) REFERENCES usuario;
ALTER TABLE tramite_revision ADD FOREIGN KEY (id_usuario) REFERENCES usuario;
ALTER TABLE tramite_evento ADD FOREIGN KEY (id_usuario) REFERENCES usuario;
